### ISSUE TITLE
Sample ideas

### ISSUE THREAD

**Issue by venkatkrk** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#1]
it will be great if we can get samples of how each command could be used.
For instance, how to retrieve records using FetchXML (or) specify filtercriteria in powershell command
How to access individual record in the resultset
How to page across pages in the resultset

Here is an example of my own contribution, where I wrote a simple script which would take a csv file of contactId's and mark them inactive. Hope it is of help.
# Ensure CRM 2015 sdk and Microsoft.Xrm.Data.PowerShell are installed
# Ensure $conn is populated by logging in using example provided here
# Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
# Import-Module Microsoft.Xrm.Data.PowerShell
# $global:conn = Get-CrmConnection -InteractiveMode
# 

$contactList=Import-CSV .\contact_dupes.csv
ForEACH ($Contact in $contactList) {
$contactid = $contact.contactId
# $contactid="449104b5-1ed0-e411-80e7-c4346bac7958"
# Retrieve CRM Record

$contactrecord = Get-CrmRecord -conn $conn -EntityLogicalName contact -id $contactid -Fields firstname,statecode
# set the status code to be inactive

$contactrecord.statecode=1
# Update CRM Record

echo $contactid
Set-CrmRecord -conn $conn -CrmRecord $contactrecord
}

**Comment by kenakamu** [comment]
Thanks for your suggestion, and that is good idea. 
The simple samples can be displayed by using Get-Help <function name> -Examples. For example, you can run Get-Help Set-CrmRecord -Examples to see examples for the command.

For update status, you can use Set-CrmRecordState function.
Set-CrmRecordState -conn $conn -EntityLogicalName contact -Id $contactid -StateCode inactive -StatusCode inactive

``` powershell
foreach($contact in $contactList) {
 #set the status code to be inactive
 Set-CrmRecordState -conn $conn -EntityLogicalName contact -Id $contact.contactId -StateCode inactive -StatusCode inactive
}
```

**Comment by venkatkrk** [comment]
Thanks, that was very helpful

**Comment by kenakamu** [comment]
Good to hear that. We appreciate any sample script suggestion!!

**Comment by rizwaans** [comment]
Hi,
I know this is quite a late comment on this post but can some one help me understand how can I execute the below foreach loop in parallel. I mean can I use **_foreach-object -parallel_** 

foreach($contact in $contactList) {
 #set the status code to be inactive
 Set-CrmRecordState -conn $conn -EntityLogicalName contact -Id $contact.contactId -StateCode inactive -StatusCode inactive
}

@venkatkrk @kenakamu

**Comment by seanmcne** [comment]
Not as-is or easily - each "thread" would need a new connection or clone to operate properly without having issues. If I were to accomplish a task that needed to be very reliably fast I'd go to .Net with C# (or your favorite language) 😀. I'm sure it's possible to eventually tune something to get parallel operations working well in powershell but I haven't had the time to dig into it much and .net surfaces a lot of nice tools to handle scenarios that normally go with code that needs to execute very quickly.

**Comment by rizwaans** [comment]
Thanks for the response @seanmcne. 
I do have code in .Net to execute using parallelism. But the reason why I'm specific about PS script is cos I have a fetch xml that needs to be updated on fly during a release. We don't know the conditions in advance that needs to be updated in fetch so I thought it would be easier to look for parallelism options in PS
