### ISSUE TITLE
Unused fields in an entity

### ISSUE THREAD

**Issue by venkatkrk** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#10]
Over time any entity in CRM has unused fields.

It will be great if we can have an example of how to find such fields.

I found this on the internet but it would be great to have this in powershell instead.

http://crmdatadetective.codeplex.com/
http://survivingcrm.com/2014/03/spring-cleaning-dynamics-crm/

-Venkat

**Comment by kenakamu** [comment]
I like this, and will write a sample for this later.
