### ISSUE TITLE
Save and publish JavaScript Web Resource

### ISSUE THREAD

**Issue by fvakiliev** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#11]
Please provide example for save and publish JavaScript Web Resource from file into specified solution.
Thanks!

**Comment by kenakamu** [comment]
Good idea. Let me figure out once I back home.meanwhile if you are curious, try create the  webresource by new-crmrecord and use publish-crmcistomization!

**Comment by fvakiliev** [comment]
Hi Kenichiro.
I wrote a powershell script for himself to save and publish resources:

```
PARAM
(
    [parameter(Mandatory=$true)]$path
)

#Import-Module Microsoft.Xrm.Data.Powershell -DisableNameChecking
$ServerUrl = "https://<crm-server-url>"
$OrganizationName = "CRMCPTEST"
$SecurePassword = [Microsoft.Xrm.Tooling.Connector.CrmServiceClient]::MakeSecureString("<Password>")
$Credentials = New-Object -TypeName 'System.Management.Automation.PSCredential' -ArgumentList "<User>", $SecurePassword
$conn = Get-CrmConnection –ServerUrl $ServerUrl -Credential $Credentials -OrganizationName $OrganizationName
if ($conn.IsReady)
{
    $message = $("Connected to CRM organization: {0} - {1}" -f $conn.ConnectedOrgFriendlyName, $conn.ConnectedOrgVersion)
    Write-Output -InputObject $message
}
else
{
    Exit;
}

# Read WebResource
$file = "";
$position = $path.IndexOf("cp_");
if($position -ge 0 ) {
    $file = $path.Substring($position);
    $file = $file.Replace('\', '/');
}
else {
    $message = $("File '{0}' has bad name! Rename webresource and try again." -f $path)
    Write-Output -InputObject $message
    Exit;
}
$wr = Get-CrmRecords -conn $conn -EntityLogicalName webresource name like $file -Fields name,content
if ($wr.Count -eq 0 ) {
    $message = $("Web resource '{0}' not found! Create it and try again." -f $file)
    Write-Output -InputObject $message
    Exit;
}
# Read javascript file
if($path.StartsWith("cp_") -eq $false)
{
    $position = $path.LastIndexOf("cp_");
    if($position -gt 0)
    {
        $file = $path.Substring($position);
        $file = $file.Replace('\', '/');
    }
}
$content = [System.IO.File]::ReadAllBytes($path);
$content64 = [System.Convert]::ToBase64String($content);
if ($content64 -ne $wr.CrmRecords[0].content) {
    Write-Host "Update it!"
    $wr.CrmRecords[0].content = $content64;
    Set-CrmRecord -conn $conn $wr.CrmRecords[0];
    Publish-CrmAllCustomization -conn $conn;
}
else {
    $message = $("Web resource '{0}' is Up to date!" -f $file)
    Write-Output -InputObject $message
    Exit;
}
```

However, there are some problems that do not let you use it:
1. The most important: if I working with CRM over VPN, this cmdlet  _**Publish-CrmAllCustomization**_ is not working (do nothing).
2. All together runs very slowly. Probably it is necessary to use low-level calls CRM API.
I have plans to use this script with **Sublime text 3 bulder**. Help me please!

Regards,
FV

**Comment by kenakamu** [comment]
Your code actually works but small correction for performance point of view.
When retrieving, please use eq and top to see if it improves the performance.

``` powershell
$wr = Get-CrmRecords webresource name eq 'new_sample.js' -Fields * -TopCount 1
```

For publish, as it publish all customizations, you may want to just publish some of them, use PublishXmlRequest sdk message to publish it.

**Comment by fvakiliev** [comment]
Ok. But will be nice if you can add some method with syntax:
`Publish-CrmRecord -EntityLogicalName <EntityTypeName> -id <GUID>`
It is posible?

**Comment by kenakamu** [comment]
You mean Publish-CrmCustomization -CustomizationType -Id like function?

**Comment by fvakiliev** [comment]
Yes!

**Comment by kenakamu** [comment]
Got it. Let us think about what we can  with version 2.3. Meanwhile please try my suggestion for your project.

**Comment by fvakiliev** [comment]
I've made changes on your recommendation. Unfortunately this does not significantly increase the speed of publication. I'll wait for Publish-CrmCustomization. ;)

Thanks!

**Comment by kenakamu** [comment]
meanwhile, could you try this works as expected?

``` powershell
$request = New-Object Microsoft.Crm.Sdk.Messages.PublishXmlRequest
$request.ParameterXml = "<importexportxml><webresources><webresource><webresourceid>{0}</webresourceid></webresource></webresources></importexportxml>" -F $wr.CrmRecords[0].webresourceid
$response = $conn.ExecuteCrmOrganizationRequest($request)
```

**Comment by fvakiliev** [comment]
ok. I'll try it tomorrow morning. We in the Urals is too late. Time to sleep.

**Comment by fvakiliev** [comment]
I tried it - does not work. It seems strange. Variable `$response` is empty..

**Comment by kenakamu** [comment]
my bad.

``` powershell
$request.ParameterXml = "<importexportxml><webresources><webresource>{0}</webresource></webresources></importexportxml>" -F $wr.CrmRecords[0].webresourceid
```

This will do.

**Comment by fvakiliev** [comment]
**Thanks** Kenichiro!

Everything works perfectly!

Regards,
FV

**Comment by kenakamu** [comment]
Added Publish-CrmCustomization function in main branch.

**Comment by fvakiliev** [comment]
Hi Kenichiro!

The new feature `Publish-CrmCustomization` works well. Thanks again!

Regards,
FV
