### ISSUE TITLE
Unable to run the View Performance script to completion

### ISSUE THREAD

**Issue by mscottsewell** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#13]
I'm able to get the script to start and run through the views, but when it reaches the end and starts to write out the list of the top 10... it fails.
Initially I found that it was a typo in the library ("verobse" instead of "verbose") - but after correcting that now I get: 

![2016-08-01_20-31-50](https://cloud.githubusercontent.com/assets/6276300/17313163/389def8c-5827-11e6-8122-4164f59dc538.png)

**Comment by kenakamu** [comment]
could you try with the latest build?

**Comment by mscottsewell** [comment]
Yes - it works with the latest build.

**Comment by kenakamu** [comment]
Thanks for the confirmation!
