### ISSUE TITLE
"Deploymentregion" Parameter in Get-CRMconnection has no function

### ISSUE THREAD

**Issue by RStadlmair** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#14]
Hi !

I tried to use "CRM Online - North America" and "North America" as deployment region, it always searches all regions . 

Is this a bug ?

Regards/Roman

**Comment by kenakamu** [comment]
Try "NorthAmerica" as one word.

**Comment by RStadlmair** [comment]
Theat worked great - Thanks - i close the issue
