### ISSUE TITLE
Opportunity to enable or disable user via powershell script

### ISSUE THREAD

**Issue by shulhachvitali** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#16]
Hi all!
 I've tried to enable disabled users, and I've faced the issue I could'n change property "isdisabled" for systemuser entity. 
I can enable user in the web, but I couldn't do it in the script. Also I found out that "IsValidForUpdate" is "False" for field "isdisabled" in the systemuser entity.
So, my question is:
How could I change user's state from enable to disable and back, using powershell?

**Comment by seanmcne** [comment]
Hi, thanks for asking the question!  These are off the top of my head, so forgive me if I missed something :) 

If you are using CRM Online: 
- you can revoke/remove the users license in AAD/o365 
- you can remove them from the security group (if the instance is secured by a security group) 

If onprem: 
- you should be able to use a setstaterequest to set the state to deactive 

Hope this helps!
