### ISSUE TITLE
How to Test & Enable mailbox in CRM Online?

### ISSUE THREAD

**Issue by brpowershell** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#19]
I am trying to use Set-CRMMailbox but couldn't figure out.  
After enabling the mailbox thru Portal, when I check with Get-CRMMailbox -userID, I see EnabledForOutgoingEmail , EnabledForIncomingEmail, EnabledForACT, OutgoingEmailStatus, ACTStatus & IncomingEmailStatus attributes are getting set as Yes or Success.

**Comment by seanmcne** [comment]
To set it up for a test & enable you can set the testemailconfigurationscheduled to True - that will queue it up for test & enable for you.
