### ISSUE TITLE
Get/Set all usersettings

### ISSUE THREAD

**Issue by venkatkrk** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#2]
Hello,

It would be great to get a list of all CRMUserSettings for a particular property. example, incomingemailfilteringmethod

The use case is to retrieve a list of all user settings for "incomingemailfilteringmethod"
Once a review is done, we need the ability to set "incomingemailfilteringmethod" to "Email messages from CRM Leads, Contacts and Accounts"

-Venkat

**Comment by kenakamu** [comment]
There are several ways to make it happen. Get-CrmUserSettings only retrieves settings for one user, you can do like below to get all user settings at once.

``` powershell
# Get incomingemailfilteringmethod settings for all usersettings record
$userSettings = Get-CrmRecords -conn $conn -EntityLogicalName usersettings -Fields incomingemailfilteringmethod
# Display the result
$usersettings.CrmRecords | select incomingemailfilteringmethod
```

And you can do following to update all 

``` powershell
$usersettings.CrmRecords | % {$_.incomingemailfilteringmethod = 2; Set-CrmUserSettings -conn $conn -CrmRecord $_}
```

The value "2" is Email messages from CRM Leads, Contacts and Accounts.
Easiest way to identify the value is to use following command.

``` powershell
$optionSet = Get-CrmEntityOptionSet -conn $conn -EntityLogicalName usersettings -FieldLogicalName incomingemailfilteringmethod
$optionSet.Items

DisplayLabel                                           PickListItemId
------------                                           --------------
All email messages                                                  0
Email messages in response to CRM email                             1
Email messages from CRM Leads, Contacts and Accounts                2
Email messages from CRM records that are email enabled              3
```

Get-CrmEntityOptionSet function retrieves optionset from an entity attribute. If you are looking into Global OptionSet, then use Get-CrmGlobalOptionSet function.

**Comment by venkatkrk** [comment]
Hi Ken,

Thanks so much!, this is brilliant. I will try to think of some common use cases as an administrator of CRM and try to write scripts and share here for others. (Or seek your help :+1: )
