### ISSUE TITLE
Solution import fails due to timeout 

### ISSUE THREAD

**Issue by shulhachvitali** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#23]
Hello!
I faced with a problem using Import-CrmSolution:
Solution size is 1.5 Mb, and import via CRM gui usually takes 2-3 minutes. but using the code I have next exeption:
![capture](https://user-images.githubusercontent.com/20320907/34606214-9a07683c-f21f-11e7-9d8d-9db494536e60.PNG)
At the same time solution was imported to CRM.
The code (run via jenkins) is:
    Param (
        [Parameter(Mandatory=$True)]
        [string]$TargetServer,
        [Parameter(Mandatory=$True)]
        [string]$organizationName2
    )
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
try {
    $conn2 = Get-CrmConnection -OrganizationName $organizationName2 -ServerUrl $targetServer -Credential $cred2 -MaxCrmConnectionTimeOutMinutes 60 -ErrorAction Stop -Verbose
}
catch {
	write-output $Error[0].Exception
}
try {
    Import-CrmSolution -conn $conn2 -SolutionFilePath $env:importedSolution -OverwriteUnManagedCustomization -ErrorAction Stop -Verbose
}
catch {
    write-output $Error[0].Exception
}
Exit $LastExitCode

Could you please give an advise how to handle a moment than solution import was finished and end the script successfully? I have tried different timeouts, it doesn't work.

'Import-CrmSolutionAsync' is working well, but is not good for this case because I'd like to get detailed error message if import is failed

Thank you in advance!

**Comment by seanmcne** [comment]
Thanks for sharing the script, can you confirm you're on the latest version of the module? 

Import-Module Microsoft.Xrm.Data.PowerShell
Get-Module -name Microsoft.xrm.data.powershell

This should show you the version, also CRM Onlines max persistent network connection will be around 5 minutes (this may be a bit longer now, but has always been lower). For this reason we have the AsyncOperationImportMethod which guards against any timeouts or failed network connections.  

One thing you could try, I'm not entirely familiar with the maxCrmConnection time for get connection and when used (at one point) it didn't work as expected. We added a function to increase the timeout, hopefully this will work for you.  Also, when importing via async you can get the details of the failure, I'll try to find the script to do that by async job id and post it back here. 

Try this once and see if it helps: 
``` powershell
Param (
[Parameter(Mandatory=$True)]
[string]$TargetServer,
[Parameter(Mandatory=$True)]
[string]$organizationName2
)
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
try {
$conn2 = Get-CrmConnection -OrganizationName $organizationName2 -ServerUrl $targetServer -Credential $cred2 -MaxCrmConnectionTimeOutMinutes 60 -ErrorAction Stop -Verbose

Set-CrmConnectionTimeout -conn $conn2 -TimeoutInSeconds 600 -SetDefault

}
catch {
write-output $Error[0].Exception
}
try {
Import-CrmSolution -conn $conn2 -SolutionFilePath $env:importedSolution -OverwriteUnManagedCustomization -ErrorAction Stop -Verbose
}
catch {
write-output $Error[0].Exception
}
Exit $LastExitCode
```

**Comment by shulhachvitali** [comment]
Thank you for reply, 
First - I have tried "maxCrmConnection" with async import 

_Import-CrmSolutionAsync -conn $conn2 -SolutionFilePath $importedSolution -OverwriteUnManagedCustomizations -PublishChanges -MaxWaitTimeInSeconds 3600 -BlockUntilImportComplete -Verbose_

And it seems, the parameter is working:

> Importing solution file  solutionSample_1.0.0.0_managed.zip into: https://myorg.api.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=8.2.0.713
> VERBOSE: OverwriteCustomizations: True
> VERBOSE: SkipDependancyCheck:     False
> VERBOSE: ImportAsHoldingSolution: False
> VERBOSE: Maximum seconds to poll: 3600
> VERBOSE: Block and wait?          True
> VERBOSE: ExecuteCrmOrganizationRequest with ExecuteAsyncRequest containing ImportSolutionRequest() this process can 
> take a while...
> VERBOSE: ImportId (asyncoperationid): 02ba0e37-94eb-e711-a94d-000d3ab50338
> VERBOSE: Import of file completed, waiting on completion of AsyncOperationId: 02ba0e37-94eb-e711-a94d-000d3ab50338
> 016 sec of: 3600 - ImportStatus: Waiting For Resources
> 021 sec of: 3600 - ImportStatus: In Progress
> ...
> 160 sec of: 3600 - ImportStatus: In Progress
> 165 sec of: 3600 - ImportStatus: In Progress
> 170 sec of: 3600 - ImportStatus: In Progress
> AsyncOperation with ID: 02ba0e37-94eb-e711-a94d-000d3ab50338 has encountered an exception: Failed - AsyncOperation 
> with Id: 02ba0e37-94eb-e711-a94d-000d3ab50338 has been either cancelled or has failed.
> Import finished
> Last exit code is 1
> Finished: SUCCESS

But log is without any useful information and script ends with wrong result of execution
An ideal behavior would be if in such cases the result of AsyncOperation execution returned as a result of the command

Example of good async import:

>244 sec of: 3600 - ImportStatus: In Progress
>Import Complete, don't forget to publish customizations.
>Import finished
> Last exit code is 0
> AsyncJobId                           ResponseName Results                                              ExtensionData   
> ----------                           ------------ -------                                              -------------   
>6b691a3e-d7eb-e711-a94d-000d3ab50338 ExecuteAsync {[AsyncJobId, 6b691a3e-d7eb-e711-a94d-000d3ab50338]} System.Runtim...

**Comment by shulhachvitali** [comment]
Modules version on the build server:
Microsoft.Xrm.Data.Powershell 2.6
Microsoft.Xrm.Data.Powershell 2.5
Microsoft.Xrm.Data.Powershell 2.4

I hope, it uses the latest

**Comment by shulhachvitali** [comment]
I modified script a little to use Set-crmconnectiontime, import has failed with the same result - by timeout
Also it is interesting, that "MaxCrmConnectionTimeOutMinutes 12" overwrites "Set-CrmConnectionTimeout -conn $conn2 -TimeoutInSeconds 600 -SetDefault":

>$conn2 = Get-CrmConnection -OrganizationName $organizationName2 -ServerUrl $targetServer -Credential $cred2 -MaxCrmConnectionTimeOutMinutes 12 -ErrorAction Stop -Verbose
  >  Set-CrmConnectionTimeout -conn $conn2 -TimeoutInSeconds 600 -SetDefault

The output:
```
Importing solution file solutionSample_1.5.0.0_managed.zip into: https://myorg.api.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=8.2.0.713
VERBOSE: OverwriteCustomizations: True
VERBOSE: SkipDependancyCheck: False
VERBOSE: ImportAsHoldingSolution: False
VERBOSE: Maximum seconds to poll for successful completion: 900
VERBOSE: Calling .ImportSolutionToCrm() this process can take minutes...
VERBOSE: ImportId: 00000000-0000-0000-0000-000000000000
System.Management.Automation.RuntimeException: The request channel timed out while waiting for a reply after 
00:11:59.9394993. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the 
Binding. The time allotted to this operation may have been a portion of a longer timeout. => The HTTP request to 
'https://myorg.api.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=8.2.0.713' has exceeded 
the allotted timeout of 00:12:00. The time allotted to this operation may have been a portion of a longer timeout. => 
The operation has timed out
Import finished
```

**Comment by seanmcne** [comment]
That is quite odd that it's overriding the timeout, I suspect that something has possibly changed in how the timeout is handled when the connection is initialized with a longer timeout. 

I also noticed that I screwed up my example for setting the timeout - it should be
```powershell
Set-CrmConnectionTimeout -conn $conn2 -TimeoutInSeconds 600
```

Below you'll find a script to analyze failed solution imports - using async is the preferred option here since Sync will depend greatly on a persistent network connection. 

The async import should still throw an exception if there's a failure within the polling window (max 900 seconds by default) and to get the failed data you can use the script below which will get all imports (as it is today but it can be modified to only get failed imports).  Inside of the xml files you'll have to look for processed="false" to get what items failed to import.  

The big thing to know is that all imports are saved with their results so you should be able to go back and analyze what exactly failed. 

``` powershell
 #dump all solution imports out to xml files for review
$results = Get-CrmRecords -EntityLogicalName importjob -FilterAttribute solutionname -FilterOperator not-like -FilterValue "activityfeeds" -Fields solutionname,progress,startedon,completedon,data -AllRows

$orderedResults = $results.CrmRecords|sort solutionname
$LastSolutionName = ""
$LastSolutionHidden = $false
$FileInfoToWrite = @()
foreach ( $record in $orderedResults) 
{
    if($LastSolutionName -eq $record.solutionname){
        if($LastSolutionHidden){
            Write-Output "Dup- Skipping: $($record.solutionname)"
            continue
        }
    }
    else{
        $LastSolutionName = ""
        $Solutions=Get-CrmRecords -EntityLogicalName solution -Fields isvisible -FilterAttribute uniquename -FilterOperator eq -FilterValue $record.solutionname
        if($Solutions.Count -eq 1){
            $LastSolutionName = $record.solutionname
            if($Solutions.CrmRecords[0].isvisible -eq "No"){
                Write-Output "Dup- Skipping: $($record.solutionname)"
                $LastSolutionHidden = $true
                continue
            }
            else{
                $LastSolutionHidden = $false
            }
        }
    }
    $fileNameForData = "$(([DateTime]($record.startedon)).ToString("yyyyMMdd_hhmmss"))_$($record.solutionname).xml"  
    $record.data > $fileNameForData
    Write-Output "Writing file with Name: $fileNameForData"
    ([xml]$record.data).InnerXml|out-file -FilePath $fileNameForData
    $FileInfoToWrite+= New-Object PSCustomObject -Property @{
        "FileName" = $fileNameForData
        "SolutionName" = $($record.solutionname) 
        "Progress" = $($record.progress)
        "StartedOn" = $($record.startedon)
        "CompletedOn" = $($record.completedon)
        "Duration" = ($record.completedon_Property.Value - $record.startedon_Property.Value).ToString()
    }
}
#dump a csv with each import job listed for review 
$FileInfoToWrite|Export-Csv SolutionImportReport.csv -NoTypeInformation 
```

**Comment by shulhachvitali** [comment]
Hello,
I have tried a code with new (initial) solution import

Import-CrmSolutionAsync -conn $conn2 -SolutionFilePath $importedSolution -OverwriteUnManagedCustomizations -PublishChanges -MaxWaitTimeInSeconds 600 -BlockUntilImportComplete -Verbose

In this case nothing is occurred in the "importjob" entity, at least I have not found my solution name
the error message:
"
AsyncOperation with ID: bb45e78b-34f5-e711-a829-000d3ab4be81 has encountered an exception: Failed - AsyncOperation with Id: bb45e78b-34f5-e711-a829-000d3ab4be81 has been either cancelled or has failed.
 "
Where is no such "importjobid"

PS C:\Users\Vitali_Shulhach> $results = Get-CrmRecords -conn $conn2 -EntityLogicalName importjob -FilterAttribute importjobid -FilterOperator like -FilterValue "bb45e78b-34f5-e711-a829-000d3ab4be81" -Fields *
WARNING: No Result
No results also searching by solution name

But there is asyncoperation with such ID and 
PS C:\Users\Vitali_Shulhach> $asyncResult = get-crmrecord -conn $conn2 -Id "bb45e78b-34f5-e711-a829-000d3ab4be81" -Fields * -EntityLogicalName asyncoperation
($asyncResult.message).Length
441214 
So, my question is:
How can I get $importId from original module code in the variable/output?) I mean this one:

AsyncOperation with ID: 012af169-36f5-e711-a829-000d3ab4be81 has encountered an exception: Failed - AsyncOperation with Id: 012af169-36f5-e711-a829-000d3ab4be81 has been either cancelled or has failed.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.6\Microsoft.Xrm.Data.Powershell.psm1:1937 char:4
throw "AsyncOperation with ID: $importId has encountered  ...

**Comment by shulhachvitali** [comment]
Well, fixed for now parsing error output and retrieving XML-report from asyncoperation by its id

**Comment by seanmcne** [comment]
Out of curiosity did you figure out what was causing the async imports to fail?  Was it just some kind of solution conflict?

**Comment by shulhachvitali** [comment]
Hi, yes, usually it caused by developing bugs) I handle it with next code:
$Error[0].Exception > "$env:Workspace\error.txt" #catching error output
    $errorstring = get-content "$env:Workspace\error.txt"
    $pattern = "[\d,\w]{8}.[\d,\w]{4}.[\d,\w]{4}.[\d,\w]{4}.[\d,\w]{12}"
    $AsyncOperationID = $errorstring.Split(' ') | Select-String -Pattern $pattern #getting ID of failed import async job
    [string]$id = $AsyncOperationID[0]
    $asyncResult = get-crmrecord -conn $conn2 -EntityLogicalName asyncoperation -Id $id -Fields * 
    ($asyncResult.message) > "$env:Workspace\RawMessageFromAsync.xml" #saving log with error for developers)

**Comment by andigwandi** [comment]
It is working for me, Please refer [this](https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/issues/205#issuecomment-481891636)
