### ISSUE TITLE
Export-CrmSolution does not work with Dynamics 365 v9

### ISSUE THREAD

**Issue by matthiashaldimann** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#25]
In Dynamics 365 instances that were updated to v9, Export-CrmSolution does not work any more.
It throws the error "Solution with name x in CRM Instance: y not found!", although the solutions are installed an can be exported manually.

The cmdlet still works in instances where identical solutions are installed, but that are not yet updated to v8.2.

A fix would be greatly appreciated. Thanks!

**Comment by seanmcne** [comment]
@matthiashaldimann - I just tested it on a v9 instance on version #9.0.1.510 and I successfully exported the solution. Try this to test the solution name - see if the records are visible. Looking at the source this is the query that runs to ensure the solution was found. 

```Powershell 
$SolutionName = "yoursolutionname"

$solutionRecords = (Get-CrmRecords -conn $conn -EntityLogicalName solution -FilterAttribute uniquename -FilterOperator "like" -FilterValue $SolutionName -Fields uniquename,publisherid,version )

$solutionRecords.CrmRecords
#if you are unable to see your solution above run this query: 

(Get-CrmRecords -conn $conn -EntityLogicalName solution -Fields uniquename,publisherid,version).CrmRecords | sort uniquename | select uniquename
```

**Comment by matthiashaldimann** [comment]
Thanks a lot, Sean! Your answer pointed me to the real issue: In fact
`$conn = Get-CrmConnection <parameters>`
does not get a working connection to the v9 instance, while it does for v8.2 instances with equivalent paramters. I was not yet able to find out why, but have found in forums that other users experience the same issue. As a workaround, I now use 
`$conn = Connect-CrmOnline -Credential $cred -ServerUrl $url`
instead for connecting to the v9 instance, which works fine, including the export of solutions.
