### ISSUE TITLE
Is there a way to retrieve the AD security group which has access to the instance using any of these powershell cmdlets?

### ISSUE THREAD

**Issue by sammy11645** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#26]

**Comment by sanjint** [comment]
You can do that with the [Microsoft.Xrm.OnlineManagementAPI](https://docs.microsoft.com/en-us/powershell/module/microsoft.xrm.onlinemanagementapi/?view=dynamics365ce-ps) module. When you retrieve the organization details by calling Get-CrmInstances it will give you the GUID of the Security Group.
Reference:
[https://docs.microsoft.com/en-us/powershell/module/microsoft.xrm.onlinemanagementapi/Get-CrmInstances?view=dynamics365ce-ps](https://docs.microsoft.com/en-us/powershell/module/microsoft.xrm.onlinemanagementapi/Get-CrmInstances?view=dynamics365ce-ps)
