### ISSUE TITLE
ManagedSolutionUpgrade.ps1 -> DeleteAndPromoteRequest throws error after 5 minutes

### ISSUE THREAD

**Issue by markus507** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#30]
If I use this code snippet in our Continous Release process the Powershell throws an error if the process takes longer than 5 Minutes. In the background the process is still running in Dynamics and completes after a while.

Any idea why the Script throws an error after exactly 5 Minutes. Timeouts are set to 15 Minutes.

**Comment by seanmcne** [comment]
I believe the network timeouts are all fixed to 5 minutes and will be closed after 5 minutes, i would suggest importing as an async job instead (using the import async method) which allow you to poll for completion (success or failure).
