### ISSUE TITLE
update Organization Information

### ISSUE THREAD

**Issue by daraar** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#31]
I am new to XRM Powershell.
I am trying to update Organization Information like Strategic Business Unit, Global Business Line, Legacy Division, Region,
Country for bulk users.

So, far  I am able to update business unit using below

#Get all business Unit and store it in variable  
$businessUnit = Get-CrmRecords -EntityLogicalName businessunit -FilterAttribute name -FilterOperator eq -FilterValue 'abc' -Fields businessunitid
$businessUnitId = $businessUnit.CrmRecords[0].businessunitid.Guid

#Set the system user business unit
Set-CrmRecord -EntityLogicalName systemuser `
-id $systemId -Fields @{ "businessunitid"=(New-CrmEntityReference -EntityLogicalName systemuser -Id $businessUnitId)}

How can I update Organization Information like Strategic Business Unit, Global Business Line in similar way?
Any help is appreciated.

**Comment by seanmcne** [comment]
What entity are the "Strategic Business Unit" and "Global Business Line" attributes on?  I'm not aware of these on the businessunit entity.  

The attributes in an out of the box businessunit entity are: 

Attribute LogicalName for businessunit
-----------
address1_addressid
address1_addresstypecode
address1_addresstypecodename
address1_city
address1_country
address1_county
address1_fax
address1_latitude
address1_line1
address1_line2
address1_line3
address1_longitude
address1_name
address1_postalcode
address1_postofficebox
address1_shippingmethodcode
address1_shippingmethodcodename
address1_stateorprovince
address1_telephone1
address1_telephone2
address1_telephone3
address1_upszone
address1_utcoffset
address2_addressid
address2_addresstypecode
address2_addresstypecodename
address2_city
address2_country
address2_county
address2_fax
address2_latitude
address2_line1
address2_line2
address2_line3
address2_longitude
address2_name
address2_postalcode
address2_postofficebox
address2_shippingmethodcode
address2_shippingmethodcodename
address2_stateorprovince
address2_telephone1
address2_telephone2
address2_telephone3
address2_upszone
address2_utcoffset
businessunitid
calendarid
costcenter
createdby
createdbyname
createdbyyominame
createdon
createdonbehalfby
createdonbehalfbyname
createdonbehalfbyyominame
creditlimit
description
disabledreason
divisionname
emailaddress
exchangerate
fileasname
ftpsiteurl
importsequencenumber
inheritancemask
isdisabled
isdisabledname
modifiedby
modifiedbyname
modifiedbyyominame
modifiedon
modifiedonbehalfby
modifiedonbehalfbyname
modifiedonbehalfbyyominame
name
organizationid
organizationidname
overriddencreatedon
parentbusinessunitid
parentbusinessunitidname
picture
stockexchange
tickersymbol
transactioncurrencyid
transactioncurrencyidname
usergroupid
utcoffset
versionnumber
websiteurl
workflowsuspended
workflowsuspendedname

**Comment by daraar** [comment]
Thanks for your response.
Here are the attributes, that I wish to change for system users.

//Strategic Business Unit
new_sbuid_Property                         : [new_sbuid, Microsoft.Xrm.Sdk.EntityReference]
new_sbuid                                  

//Global Business Line
new_gblid_Property                         : [new_gblid, Microsoft.Xrm.Sdk.EntityReference]
new_gblid                                

//Legacy Division
new_divisionid_Property                    : [new_divisionid, Microsoft.Xrm.Sdk.EntityReference]
new_divisionid                             : IA

//Location
new_locationid_Property                    : [new_locationid, Microsoft.Xrm.Sdk.EntityReference]
new_locationid	                        

//Region
new_regionid_Property                      : [new_regionid, Microsoft.Xrm.Sdk.EntityReference]
new_regionid                            

//Country
new_countryid_Property                     : [new_countryid, Microsoft.Xrm.Sdk.EntityReference]
new_countryid

**Comment by daraar** [comment]
I want t change the below lookup values for system users.

Get-CrmEntityAttributes -EntityLogicalName systemuser | select logicalname,AttributeType | sort logicalname


LogicalName                                        AttributeType
new_sbuid						Lookup
new_gblid						Lookup
new_divisionid						Lookup
new_locationid					Lookup
new_regionid						Lookup

**Comment by seanmcne** [comment]
These are custom attributes - they all appear to be lookups which will be an “EntityReference”. An entity reference is an object that defines the EntityLogicalName of the referencing entity and the Guid identifier if the record. 

You would set each field equal to a value of something like: (new-crmEntityReference -EntityLogicalName “new_entityname” -id “GuidValue”)

Hope this helps!

**Comment by daraar** [comment]
Thanks a lot, it is really helpful.
I tried to set the below:
Set-CrmRecord -EntityLogicalName systemuser -Id xxxxxxxx-xxxx-xxxx-xxx-xxxccxxx -Fields @{"new_sbuid"="Sample"}

and got the error , these are lookup values:
Error converting to Property: Attribute [new_sbuid], Attribute type [lookup] of Entity [systemuser] with value of type [System.String]: 
[System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Microsoft.Xrm.Sdk.EntityReference'.
   at Microsoft.Crm.BusinessEntities.LookupPropertyConverter.InternalFromEntity(ICrmConversionContext conversionContext, AttributeMetadata attributeMetadata, 
Object value, String formattedValue)
   at Microsoft.Crm.BusinessEntities.PropertyConverterBase.<>c__DisplayClass7_0.<FromEntity>b__0()
   at Microsoft.Crm.BusinessEntities.PropertyConverterBase.InternalConvertFrom[T](Guid orgId, AttributeMetadata attributeMetadata, Object value, Func`1 
converterFunction)]

I am sorry for being novice with this references,

**Comment by daraar** [comment]
Thank you, its really helpful.
can you kindly tell me how to get GuidValue of custom attributes?

**Comment by seanmcne** [comment]
The guid is the identifier of the related record (the lookup). If you want to get the record Id you can use PowerShell to search and find it. Also, you can open the record in dynamics and “pop out” the record and get the guid from the URL address bar. Finally, you can use a browser addin like LevelUp. Hope that helps!

**Comment by daraar** [comment]
Thank you, I can retrieve using addins or with email a link method. But there are more than 200 attributes and records, so was looking for an option using Powershell

**Comment by seanmcne** [comment]
Hi Daraar, I think we'll need to know more about the situation/context.  If it's data in the system, then you can use this powershell module to find the data.  The point I was making above is, if you know the ID of a given record that you want attributes for, then you use get-crmrecord.  If you want to query for multiple records or a non unique attribute value then you use get-crmrecords or get-crmrecordsbyfetch (which allows you to use a more complex fetchxml query).  

If you're familiar with powershell, feel free to use get-help on the cmdlets for this module and explore the examples in our help documentation.  Also check out the samples site for more obscure samples or situations that might require a little more scripting or custom objects, etc. We are missing some basic samples, although those basic samples are just part of the help - such as:
```powershell
get-help get-crmrecords
get-help set-crmrecord 
#etc
```

Samples Repo: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell.Samples

Module Repo: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell 

If you find there's a missing sample the community would benefit from (that isn't already covered in the help, or is more of a walk-through) i'd encourage you to issue a PR to this samples site and work with us on getting one included. 

Thanks!
