### ISSUE TITLE
In CRM Online, find the top 10 entites using maximum space

### ISSUE THREAD

**Issue by venkatkrk** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#4]
It will be great to get the top 10 entities by storage space used
This will help identify data management/maintenance tasks.

In response, it will be great to see entity name, space used, record count

**Comment by kenakamu** [comment]
Unfortunately, there is no API available to get that information at the moment. You can run Get-CrmRecordsCount to check record counts for each entity.

**Comment by venkatkrk** [comment]
#Wrote a small ps script
#Retrieve full entity list from CRM
$entitylist =  Get-CrmEntityAllMetadata | select logicalName

# Print record count of each entity

ForEACH ($entity in $entitylist) {
$entity = $entity.LogicalName.Trim()

#if ( $entity -eq "account") {
$count = Get-CrmRecordsCount -EntityLogicalName $entity
Write-Output ( $entity + "," + $count)
#}
}

**Comment by kenakamu** [comment]
good sample. I will put it as part of sample list.
