### ISSUE TITLE
Delete activitypointer entry given Id

### ISSUE THREAD

**Issue by venkatkrk** [seanmcne/Microsoft.Xrm.Data.PowerShell.Samples#7]
Tried to use Remove-CRMRecord to delete activities but got a error message as below 

Remove-CrmRecord -conn $conn -EntityLogicalName activitypointer -Id 5e24fedb-a052-e511-8103-c4346bad2660

The 'Delete' method does not support entities of type 'activitypointer'.

**Comment by kenakamu** [comment]
You should simply delete actual record type like Letter, Task, Appointment.
